#!/bin/sh
uglifyjs src/perfect-scrollbar.js -o min/perfect-scrollbar.min.js
uglifyjs src/perfect-scrollbar.js src/jquery.mousewheel.js -o min/perfect-scrollbar.with-mousewheel.min.js
cleancss src/perfect-scrollbar.css -o min/perfect-scrollbar.min.css
