baseURL = "https://tst.tailwind-elements.com/"
languageCode = "en-us"
title = "Tailwind Elements - Bootstrap components recreated with Tailwind"
theme = "ga-hugo-theme"
enableInlineShortcodes = "true"

[params]
recaptchaPublicKey = "6LcpeIgkAAAAALdS4oKmgSPscp8ZYFLjavMstifN"

[[menu.gettingstarted]]
identifier = "design-system"
name = "Design system"
url = "https://material-minimal.com/"
weight = 2